apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    app: nginxlab
spec:
  containers:
  - name: nginx
    image: lauracode/nginxlab:1.4
    ports:
    - containerPort: 80
    volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf

  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config