apiVersion: v1
kind: PersistentVolume

metadata:
  name: nginx-pv

spec:
  capacity:
    storage: 5Mi

  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /mnt/data/nginx